### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by arrowrowe** [swaylq/uranus#1]
- [ ] A brief introduction. (Plain text)
- [ ] URL for a live demo.
- [ ] Some screenshots.
- [ ] A feature list.
- [ ] Installation guide.
- [ ] Contribution guide.
- [ ] License.

**Comment by at15** [comment]
btw: license file?

**Comment by arrowrowe** [comment]
re @at15: added into list now.

**Comment by at15** [comment]
@arrowrowe I bet 0.5 RMB that this issue will be ignored

**Comment by arrowrowe** [comment]
Close due to being ignored for too long. :sob:

~~Bad @swaylq.~~

**Comment by at15** [comment]
@arrowrowe patpat 咩抖酱
